Sort media by default semantics, includes test, and VS test runner fo…
OpenRealEstate/OpenRealEstate.NET pull request #28
Opened 2017-02-16 04:36 UTC by ctolkien

…r xunit

2017-02-16 08:47 UTC, PureKrome requested changes

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Core/Models/Media.cs
> +
Delete empty line.

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Core/Models/Media.cs
> +
Delete line.

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +            //Assert jumbed order
Don't need these 3x asserts.

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +            var media1 = new Media { Order = 1 };
Add the text `// Arrange.` above this line.

e.g.

```
// Arrange.
var media1 = new M....
```

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +            //purposely put these in jumbled order
space between `//` and `P`.
`// Purpos....`

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +            //Assert jumbed order
Space and `.`

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +            //Act
Space and .

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +            //Assert
Space and .

2017-02-16 08:47 UTC, PureKrome commented on Code/OpenRealEstate.Tests/Models/MediaTests.cs
> +        public void MediaShouldSortByValueOfOrderProperty()
Rename: `GivenACollectionOfMedias_CompareTo_CorrectlySortsTheCollection`

2017-02-16 08:48 UTC, PureKrome commented
Also, change the test from a `[Fact]` to:

```
[Theory]
[MemberData(nameof(ValidData))]
public void GivenACollectionOfMedias_CompareTo_CorrectlySortsTheCollection(Media[] medias)
{
```

and make `ValidData` something like...

```
public static IEnumerable<object[]> ValidData => new[]
{
    new object[]
    {
        // Collection sorted.
    },
    new object[]
    {
        // Collection but unsorted.
    }
};
```


Also, need some tests for an empty collection (is that considered a valid test?)

also tests for comparing things that are not the same. This checks for the `ArgumentException`.

eg. Order vs a Cow or whatever.

2017-02-16 22:36 UTC, ctolkien commented
>Also, need some tests for an empty collection (is that considered a valid test?)

How would we test that? That it doesn't throw?

2017-02-16 22:43 UTC, PureKrome commented
> How would we test that? That it doesn't throw?

Because that's a valid scenario and whatever the correct solution is (under that scenario), needs to be 
1) considered
2) tested.

2017-12-04 05:11 UTC, PureKrome commented
Manually ended up adding in these changes (or similar) to #42 .

2018-06-04 02:17 UTC, closed without merging